#!/usr/bin/env zsh
set -Eeuo pipefail

trap 'err=$?; echo "Failed to backup database! Status Code: $err"; exit $err' ERR 

db_name='stats.sqlite3'
db_backup='stats.sqlite3.bak'

record() {
  printf "+ $*\n"
  $*
}

echo "Backing up $db_name..."
record sqlite3 -readonly ./db/$db_name ".backup main ./db/$db_backup"
echo "$db_name backed up to $db_backup successfully!"
